name             'commvault'
maintainer       'DMS Team'
maintainer_email 'int-dms@schubergphilis.com'
license          'Apache-2.0'
description      'Installs and Configured CommVault client software'
version          '1.2.1'
chef_version     '>= 14.0'

issues_url 'https://github.com/sbp-cookbooks/commvault/issues'
source_url 'https://github.com/sbp-cookbooks/commvault'

supports 'centos'
supports 'debian'
supports 'redhat'
supports 'windows'
