---
name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@0.0.6
    with:
      gems: "deepsort"
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [lint-unit]
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.CI_SSH_PRIVATE_KEY }}
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Release
        run: |
          COOKBOOK_NAME=$(grep "^name" metadata.rb | awk '{print $2}' | sed s/\'//g)
          COOKBOOK_VERSION=$(grep "^version" metadata.rb | awk '{print $2}' | sed s/\'//g)
          echo "NAME: ${COOKBOOK_NAME}"
          echo "VERSION: ${COOKBOOK_VERSION}"
          if git tag | grep -q v$COOKBOOK_VERSION; then
            echo "Cookbook version is already tagged, skipping job"
            exit 0
          fi
          if knife supermarket show $COOKBOOK_NAME $COOKBOOK_VERSION; then
            echo "Cookbook version already exists on supermarket, skipping job"
            exit 0
          fi
          git config --global user.email "cookbooks@schubergphilis.com"
          git config --global user.name "SBP Cookbooks CI"
          git tag v$COOKBOOK_VERSION
          git push origin v$COOKBOOK_VERSION
          echo "$SUPERMARKET_PEM" > supermarket.pem
          knife supermarket share -o .. --config-option=node_name=sbp-cookbooks --config-option=client_key=supermarket.pem $COOKBOOK_NAME
        env:
          CHEF_LICENSE: accept-no-persist
          SUPERMARKET_PEM: ${{ secrets.SUPERMARKET_PEM }}
