---
name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.CI_SSH_PRIVATE_KEY }}
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Release
        run: |
          COOKBOOK_NAME=$(grep "^name" metadata.rb | awk '{print $2}' | sed s/\'//g)
          COOKBOOK_VERSION=$(grep "^version" metadata.rb | awk '{print $2}' | sed s/\'//g)
          if knife supermarket show $COOKBOOK_NAME $COOKBOOK_VERSION; then
            echo "Cookbook version already exists on supermarket, skipping job"
            exit 0
          fi
          git config --global user.email "cookbooks@schubergphilis.com"
          git config --global user.name "SBP Cookbooks CI"
          echo "$SUPERMARKET_PEM" > supermarket.pem
          knife supermarket share -o .. --config-option=node_name=sbp-cookbooks --config-option=client_key=supermarket.pem $COOKBOOK_NAME
        env:
          CHEF_LICENSE: accept-no-persist
          SUPERMARKET_PEM: ${{ secrets.SUPERMARKET_PEM }}
